To give you an idea of the performance difference, consider a NumPy array of one
million integers, and the equivalent Python list:

In [2]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for i in range(10):my_arr2 = my_arr *2

Wall time: 16 ms


In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 18.9 ms


In [5]:
%time for i in range(10): my_list2 = [x *2 for x in my_list]

Wall time: 780 ms


NumPy-based algorithms are generally 10 to 100 times faster (or more) than their
pure Python counterparts and use significantly less memory.

## 4.1 The NumPy ndarray: A Multidimensional Array Object 

In [6]:
data = np.random.randn(2,3)
data

array([[ 1.19716046, -0.95962394, -1.27889673],
       [ 0.21382759, -1.85206261,  1.38007697]])

In [7]:
data*10

array([[ 11.97160463,  -9.59623936, -12.78896728],
       [  2.1382759 , -18.52062615,  13.80076968]])

In [8]:
data + data

array([[ 2.39432093, -1.91924787, -2.55779346],
       [ 0.42765518, -3.70412523,  2.76015394]])

An ndarray is a generic multidimensional container for homogeneous data; that is, all
of the elements must be the same type.

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

###  Creating ndarrays

In [11]:
data1= [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2= [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim # 几维？

2

In [14]:
arr2.shape

(2, 4)

In [15]:
# zeros and ones create arrays of 0s or 1s
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# empty creates an array without initializing its values to any particular value.
np.empty((2, 3, 2))

array([[[9.64800086e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.23053953e-307, 3.92574739e+179]],

       [[1.60274246e-051, 1.00389035e-042],
        [1.13053667e-042, 5.98443718e+174],
        [1.73997681e+184, 4.50642136e+174]]])

In [19]:
# arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [21]:
 arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [22]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [23]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [24]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [25]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [26]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

###  Arithmetic with NumPy Arrays

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [32]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

###  Basic Indexing and Slicing

In [33]:
arr = np.arange(10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5:8]

array([5, 6, 7])

In [36]:
arr[5:8] = 12

In [37]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

An important first distinction from Python’s built-in lists is that array slices are views on the original array.
This means that the data is not copied, and any modifications to the view will be
reflected in the source array.

In [38]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [39]:
arr_slice[1] = 12345

In [40]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [42]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])